-- COMANDO PARA CRIAR COMANDOS NO BANCO DE DADOS
CREATE DATABASE ESCOLA_JULIA;

CREATE DATABASE ESCOLA_JULIA2;

-- COMANDO PARA APAGAR COMANDOS NO BANCO DE DADOS

DROP DATABASE ESCOLA_JULIA2;

-- COMANDO PARA ATIVAR BCD

 USE ESCOLA_JULIA;
 
 -- MOSTRAR TABELAS NO BCD

 SHOW TABLES;
 
 -- COMANDO PARA CRIAR TABELAS
 
   CREATE TABLE CLIENTES (
 ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
 NOME VARCHAR(60) NOT NULL,
 TELEFONE VARCHAR(14) NOT NULL,
 DATA_NASCIMENTO DATE NOT NULL,
 CPF VARCHAR(11) NOT NULL,
 ENDERECO VARCHAR(100) NOT NULL
 );
 
 CREATE TABLE PRODUTOS (
 ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
 VALOR DECIMAL NOT NULL,
 NOME VARCHAR(15) NOT NULL,
 TIPO VARCHAR(20) NOT NULL,
 MARCA VARCHAR(20) NOT NULL,
 TAMANHO VARCHAR(20) NOT NULL
 );

 CREATE TABLE FUNCIONARIOS (
 ID_FUNCIONARIOS INT AUTO_INCREMENT PRIMARY KEY,
 NOME VARCHAR(15) NOT NULL,
 IDADE INT NOT NULL,
 META DECIMAL NOT NULL,
 FUNCAO VARCHAR(15) NOT NULL,
 TURNO VARCHAR(10) NOT NULL
 );
 
 -- COMANDO PARA ALTERAR TABELAS
 -- ADD UM NOVO ATRIBUTO
 
  ALTER TABLE CLIENTES ADD IDADE INT NOT NULL;
  
  -- ALTERAR UM TIPO  DE DADOS E TAMANHO DO ATRIBUTO
  ALTER TABLE CLIENTES MODIFY TELEFONE VARCHAR(15);

  
-- RENOMEAR ALGUM NOME DE ATRBT

-- ALTER TABLE CLIENTES CHANGE TELEFONE CELULAR(15);

-- EXCLUIR ATRBT 
-- ALTER TABLE CLIENTES DROP COLUMN TELEFONE;

-- LIMPAR DADOS DA TABELA
-- TRUNCATE TABLE CLIENTES;

